import type { GadgetSettings } from "gadget-server";

export const settings: GadgetSettings = {
  type: "gadget/settings/v1",
  frameworkVersion: "v1.3.0",
  plugins: {
    connections: {
      shopify: {
        apiVersion: "2025-01",
        enabledModels: [
          "shopifyApp",
          "shopifyAppInstallation",
          "shopifyAppSubscription",
          "shopifyCollect",
          "shopifyCollection",
          "shopifyCompany",
          "shopifyCustomer",
          "shopifyCustomerAddress",
          "shopifyCustomerMergeable",
          "shopifyFile",
          "shopifyProduct",
          "shopifyProductMedia",
          "shopifyProductOption",
          "shopifyProductVariant",
          "shopifyProductVariantMedia",
          "shopifyTheme",
        ],
        type: "partner",
        scopes: [
          "read_customers",
          "write_customers",
          "read_customer_merge",
          "read_products",
          "write_products",
          "read_draft_orders",
          "write_draft_orders",
          "read_price_rules",
          "write_price_rules",
          "read_script_tags",
          "write_script_tags",
          "read_store_credit_accounts",
          "read_themes",
          "write_themes",
          "unauthenticated_read_checkouts",
          "unauthenticated_write_checkouts",
          "unauthenticated_read_content",
          "unauthenticated_read_customer_tags",
          "unauthenticated_read_customers",
          "unauthenticated_write_customers",
          "unauthenticated_read_metaobjects",
          "unauthenticated_read_product_inventory",
          "unauthenticated_read_product_listings",
          "unauthenticated_read_product_pickup_locations",
          "unauthenticated_read_product_tags",
          "unauthenticated_read_selling_plans",
        ],
        customerAuthenticationEnabled: true,
      },
    },
  },
};
