import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "shopifyShop" model, go to https://quotes-draft-order-request.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v1",
  storageKey: "DataModel-Shopify-Shop",
  fields: {
    AppPlan: {
      type: "belongsTo",
      parent: { model: "AppPlan" },
      storageKey: "PJ4eMZ_4aMiw",
    },
    activeRecurringSubscriptionId: {
      type: "string",
      storageKey: "9ClQqQ4f1z6u",
    },
    analytics: {
      type: "hasOne",
      child: { model: "analytics", belongsToField: "shop" },
      storageKey: "lO0Fqlzphpwr",
    },
    confirmationUrl: { type: "string", storageKey: "F3U7mUix4H5L" },
    formFields: {
      type: "hasOne",
      child: { model: "formFields", belongsToField: "shop" },
      storageKey: "fy6g_qRUb-Oa",
    },
    onBording: {
      type: "boolean",
      default: true,
      storageKey: "gzRW3K3l7sN7",
    },
    quoteSetting: {
      type: "hasOne",
      child: { model: "quoteSetting", belongsToField: "shop" },
      storageKey: "xyOYC3xL64wi",
    },
    quotes: {
      type: "hasOne",
      child: { model: "quotes", belongsToField: "shop" },
      storageKey: "YVhlvA-U4Tuu",
    },
    setting: {
      type: "hasOne",
      child: { model: "setting", belongsToField: "shop" },
      storageKey: "2FE0NmS5gCr7",
    },
    shopifyApp: {
      type: "hasOne",
      child: { model: "shopifyApp", belongsToField: "shopifyShop" },
      storageKey: "vQqku-khf8sv",
    },
    usedTrialMinutes: { type: "number", storageKey: "ZI_AndW9gJKe" },
    usedTrialMinutesUpdatedAt: {
      type: "dateTime",
      includeTime: true,
      storageKey: "gOmySqd6Y1yJ",
    },
  },
  shopify: {
    fields: [
      "address1",
      "address2",
      "appInstallations",
      "appSubscriptions",
      "checkoutApiSupported",
      "city",
      "collections",
      "collects",
      "company",
      "cookieConsentLevel",
      "country",
      "countryCode",
      "countryName",
      "countyTaxes",
      "currency",
      "customerAccountsV2",
      "customerAddresses",
      "customerEmail",
      "customerMergeables",
      "customers",
      "domain",
      "eligibleForCardReaderGiveaway",
      "eligibleForPayments",
      "email",
      "enabledPresentmentCurrencies",
      "files",
      "finances",
      "forceSsl",
      "gdprRequests",
      "googleAppsDomain",
      "googleAppsLoginEnabled",
      "hasDiscounts",
      "hasGiftCards",
      "hasStorefront",
      "ianaTimezone",
      "latitude",
      "longitude",
      "marketingSmsContentEnabledAtCheckout",
      "moneyFormat",
      "moneyInEmailsFormat",
      "moneyWithCurrencyFormat",
      "moneyWithCurrencyInEmailsFormat",
      "multiLocationEnabled",
      "myshopifyDomain",
      "name",
      "passwordEnabled",
      "phone",
      "plan",
      "planDisplayName",
      "planName",
      "preLaunchEnabled",
      "primaryLocale",
      "productMedia",
      "productOptions",
      "productVariantMedia",
      "productVariants",
      "products",
      "province",
      "provinceCode",
      "requiresExtraPaymentsAgreement",
      "setupRequired",
      "shopOwner",
      "shopifyCreatedAt",
      "shopifyUpdatedAt",
      "source",
      "syncs",
      "taxShipping",
      "taxesIncluded",
      "themes",
      "timezone",
      "transactionalSmsDisabled",
      "weightUnit",
      "zipCode",
    ],
  },
};
