import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "shopifyShop" model, go to https://quotes-draft-order-request.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v2",
  storageKey: "DataModel-Shopify-Shop",
  fields: {
    AppPlan: {
      type: "belongsTo",
      parent: { model: "AppPlan" },
      storageKey: "PJ4eMZ_4aMiw",
      searchIndex: false,
    },
    activeRecurringSubscriptionId: {
      type: "string",
      storageKey: "9ClQqQ4f1z6u",
      filterIndex: false,
      searchIndex: false,
    },
    analytics: {
      type: "hasOne",
      child: { model: "analytics", belongsToField: "shop" },
      storageKey: "lO0Fqlzphpwr",
    },
    confirmationUrl: {
      type: "string",
      storageKey: "F3U7mUix4H5L",
      filterIndex: false,
      searchIndex: false,
    },
    cookieConsentLevel: {
      type: "string",
      storageKey:
        "ModelField-DataModel-Shopify-Shop-cookie_consent_level::FieldStorageEpoch-DataModel-Shopify-Shop-cookie_consent_level-initial",
      filterIndex: false,
      searchIndex: false,
    },
    currencyBackup: {
      type: "string",
      storageKey:
        "ModelField-DataModel-Shopify-Shop-currency::FieldStorageEpoch-DataModel-Shopify-Shop-currency-initial",
      filterIndex: false,
      searchIndex: false,
    },
    eligibleForCardReaderGiveaway: {
      type: "boolean",
      storageKey:
        "ModelField-DataModel-Shopify-Shop-eligible_for_card_reader_giveaway::FieldStorageEpoch-DataModel-Shopify-Shop-eligible_for_card_reader_giveaway-initial",
      filterIndex: false,
      searchIndex: false,
    },
    enabledPresentmentCurrenciesBackup: {
      type: "json",
      storageKey:
        "ModelField-DataModel-Shopify-Shop-enabled_presentment_currencies::FieldStorageEpoch-DataModel-Shopify-Shop-enabled_presentment_currencies-initial",
      filterIndex: false,
      searchIndex: false,
    },
    forceSsl: {
      type: "boolean",
      storageKey:
        "ModelField-DataModel-Shopify-Shop-force_ssl::FieldStorageEpoch-DataModel-Shopify-Shop-force_ssl-initial",
      filterIndex: false,
      searchIndex: false,
    },
    formFields: {
      type: "hasOne",
      child: { model: "formFields", belongsToField: "shop" },
      storageKey: "fy6g_qRUb-Oa",
    },
    onBording: {
      type: "boolean",
      default: true,
      storageKey: "gzRW3K3l7sN7",
      filterIndex: false,
      searchIndex: false,
    },
    quoteSetting: {
      type: "hasOne",
      child: { model: "quoteSetting", belongsToField: "shop" },
      storageKey: "xyOYC3xL64wi",
    },
    quotes: {
      type: "hasOne",
      child: { model: "quotes", belongsToField: "shop" },
      storageKey: "YVhlvA-U4Tuu",
    },
    setting: {
      type: "hasOne",
      child: { model: "setting", belongsToField: "shop" },
      storageKey: "2FE0NmS5gCr7",
    },
    shopifyApp: {
      type: "hasOne",
      child: { model: "shopifyApp", belongsToField: "shopifyShop" },
      storageKey: "vQqku-khf8sv",
    },
    usedTrialMinutes: {
      type: "number",
      storageKey: "ZI_AndW9gJKe",
      filterIndex: false,
      searchIndex: false,
    },
    usedTrialMinutesUpdatedAt: {
      type: "dateTime",
      includeTime: true,
      storageKey: "gOmySqd6Y1yJ",
      filterIndex: false,
      searchIndex: false,
    },
    weightUnitBackup: {
      type: "string",
      storageKey:
        "ModelField-DataModel-Shopify-Shop-weight_unit::FieldStorageEpoch-DataModel-Shopify-Shop-weight_unit-initial",
      filterIndex: false,
      searchIndex: false,
    },
  },
  shopify: {
    fields: {
      address1: { filterIndex: false, searchIndex: false },
      address2: { filterIndex: false, searchIndex: false },
      alerts: { filterIndex: false, searchIndex: false },
      appInstallations: true,
      appSubscriptions: true,
      billingAddress: { filterIndex: false },
      checkoutApiSupported: {
        filterIndex: false,
        searchIndex: false,
      },
      city: { filterIndex: false, searchIndex: false },
      collections: true,
      collects: true,
      company: true,
      countriesInShippingZones: {
        filterIndex: false,
        searchIndex: false,
      },
      country: { filterIndex: false, searchIndex: false },
      countryCode: { filterIndex: false, searchIndex: false },
      countryName: { filterIndex: false, searchIndex: false },
      countyTaxes: { filterIndex: false, searchIndex: false },
      currency: { filterIndex: false, searchIndex: false },
      currencyFormats: { filterIndex: false, searchIndex: false },
      customerAccounts: { filterIndex: false, searchIndex: false },
      customerAccountsV2: { filterIndex: false, searchIndex: false },
      customerAddresses: true,
      customerEmail: { filterIndex: false, searchIndex: false },
      customerMergeables: true,
      customers: true,
      description: { filterIndex: false },
      domain: { filterIndex: false, searchIndex: false },
      eligibleForPayments: { filterIndex: false, searchIndex: false },
      email: { filterIndex: false, searchIndex: false },
      enabledPresentmentCurrencies: {
        filterIndex: false,
        searchIndex: false,
      },
      files: true,
      finances: { filterIndex: false, searchIndex: false },
      gdprRequests: true,
      googleAppsDomain: { filterIndex: false, searchIndex: false },
      googleAppsLoginEnabled: {
        filterIndex: false,
        searchIndex: false,
      },
      hasDiscounts: { filterIndex: false, searchIndex: false },
      hasGiftCards: { filterIndex: false, searchIndex: false },
      hasStorefront: { filterIndex: false, searchIndex: false },
      ianaTimezone: { filterIndex: false, searchIndex: false },
      latitude: { filterIndex: false, searchIndex: false },
      longitude: { filterIndex: false, searchIndex: false },
      marketingSmsContentEnabledAtCheckout: {
        filterIndex: false,
        searchIndex: false,
      },
      moneyFormat: { filterIndex: false, searchIndex: false },
      moneyInEmailsFormat: { filterIndex: false, searchIndex: false },
      moneyWithCurrencyFormat: {
        filterIndex: false,
        searchIndex: false,
      },
      moneyWithCurrencyInEmailsFormat: {
        filterIndex: false,
        searchIndex: false,
      },
      multiLocationEnabled: {
        filterIndex: false,
        searchIndex: false,
      },
      myshopifyDomain: { searchIndex: false },
      name: { filterIndex: false, searchIndex: false },
      orderNumberFormatPrefix: {
        filterIndex: false,
        searchIndex: false,
      },
      orderNumberFormatSuffix: {
        filterIndex: false,
        searchIndex: false,
      },
      passwordEnabled: { filterIndex: false, searchIndex: false },
      phone: { filterIndex: false, searchIndex: false },
      plan: { filterIndex: false, searchIndex: false },
      planDisplayName: { filterIndex: false, searchIndex: false },
      planName: { filterIndex: false, searchIndex: false },
      planPublicDisplayName: true,
      preLaunchEnabled: { filterIndex: false, searchIndex: false },
      primaryLocale: { filterIndex: false, searchIndex: false },
      productMedia: true,
      productOptions: true,
      productVariantMedia: true,
      productVariants: true,
      products: true,
      province: { filterIndex: false, searchIndex: false },
      provinceCode: { filterIndex: false, searchIndex: false },
      requiresExtraPaymentsAgreement: {
        filterIndex: false,
        searchIndex: false,
      },
      resourceLimits: { filterIndex: false, searchIndex: false },
      richTextEditorUrl: { filterIndex: false, searchIndex: false },
      setupRequired: { filterIndex: false, searchIndex: false },
      shipsToCountries: { filterIndex: false, searchIndex: false },
      shopAddress: { filterIndex: false, searchIndex: false },
      shopOwner: { filterIndex: false, searchIndex: false },
      shopifyCreatedAt: { filterIndex: false, searchIndex: false },
      shopifyUpdatedAt: { filterIndex: false, searchIndex: false },
      source: { filterIndex: false, searchIndex: false },
      syncs: true,
      taxShipping: { filterIndex: false, searchIndex: false },
      taxesIncluded: { filterIndex: false, searchIndex: false },
      themes: true,
      timezone: { filterIndex: false, searchIndex: false },
      timezoneAbbreviation: {
        filterIndex: false,
        searchIndex: false,
      },
      timezoneOffset: { filterIndex: false, searchIndex: false },
      timezoneOffsetMinutes: {
        filterIndex: false,
        searchIndex: false,
      },
      transactionalSmsDisabled: {
        filterIndex: false,
        searchIndex: false,
      },
      unitSystem: { filterIndex: false, searchIndex: false },
      url: { filterIndex: false },
      weightUnit: { filterIndex: false, searchIndex: false },
      zipCode: { filterIndex: false, searchIndex: false },
    },
  },
};
