import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "setting" model, go to https://quotes-draft-order-request.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v2",
  storageKey: "ell5Ds4nUJGp",
  fields: {
    add_custom_item_btn_bg_color: {
      type: "string",
      default: "#000000",
      storageKey: "Q_xEMdUKvD9D",
      filterIndex: false,
      searchIndex: false,
    },
    add_custom_item_btn_color: {
      type: "string",
      default: "#FFFFFF",
      storageKey: "dILW9LOpKXG2",
      filterIndex: false,
      searchIndex: false,
    },
    add_custom_item_btn_text: {
      type: "string",
      default: "Add Item",
      storageKey: "adYFCoAqdeKn",
      filterIndex: false,
      searchIndex: false,
    },
    add_custom_item_checkbox_label: {
      type: "string",
      default: "Add Custom Line Item?",
      storageKey: "TeGC7SJdaD6V",
      filterIndex: false,
      searchIndex: false,
    },
    add_custom_item_title: {
      type: "string",
      default: "Custom Line Items",
      storageKey: "h0JSvhyOxkxn",
      filterIndex: false,
      searchIndex: false,
    },
    add_custom_item_title_align: {
      type: "enum",
      default: "1",
      acceptMultipleSelections: false,
      acceptUnlistedOptions: false,
      options: ["1", "2", "3"],
      storageKey: "xU9jF8ZCBdw5",
      filterIndex: false,
      searchIndex: false,
    },
    add_custom_item_title_color: {
      type: "string",
      default: "#000000",
      storageKey: "nijlbt_uAFLZ",
      filterIndex: false,
      searchIndex: false,
    },
    add_to_cart_btn_bg_color: {
      type: "string",
      default: "#000000",
      storageKey: "LXf_tYH_wGuw",
      filterIndex: false,
      searchIndex: false,
    },
    add_to_cart_btn_bg_hover_color: {
      type: "string",
      default: "#000000",
      storageKey: "3Xmqkn9dgobu",
      filterIndex: false,
      searchIndex: false,
    },
    add_to_cart_btn_border_color: {
      type: "string",
      default: "#000000",
      storageKey: "uasQldPhpr6t",
      filterIndex: false,
      searchIndex: false,
    },
    add_to_cart_btn_border_hover_color: {
      type: "string",
      default: "#000000",
      storageKey: "HDJQ3RLqsoEO",
      filterIndex: false,
      searchIndex: false,
    },
    add_to_cart_btn_font: {
      type: "string",
      storageKey: "vsr_l52w-Nf9",
      filterIndex: false,
      searchIndex: false,
    },
    add_to_cart_btn_text: {
      type: "string",
      default: "Add to quote",
      storageKey: "KHEl0w9yiaSa",
      filterIndex: false,
      searchIndex: false,
    },
    add_to_cart_btn_text_color: {
      type: "string",
      default: "#FFFFFF",
      storageKey: "mIl4e65q_exK",
      filterIndex: false,
      searchIndex: false,
    },
    add_to_cart_btn_text_hover_color: {
      type: "string",
      default: "#FFFFFF",
      storageKey: "SvkGlSmI8M6r",
      filterIndex: false,
      searchIndex: false,
    },
    is_add_custom_item: {
      type: "boolean",
      default: true,
      storageKey: "KGGompozU2Lt",
      filterIndex: false,
      searchIndex: false,
    },
    is_effect_quote_button: {
      type: "enum",
      default: "1",
      acceptMultipleSelections: false,
      acceptUnlistedOptions: false,
      options: ["0", "1"],
      storageKey: "FqIAgeFiQVlF",
      filterIndex: false,
      searchIndex: false,
    },
    is_quote_enable: {
      type: "string",
      default: "1",
      storageKey: "wdUSqMbkZFnt",
      filterIndex: false,
      searchIndex: false,
    },
    is_redirect: {
      type: "enum",
      default: "0",
      acceptMultipleSelections: false,
      acceptUnlistedOptions: false,
      options: ["0", "1"],
      storageKey: "9Zn-T49BZZCm",
      filterIndex: false,
      searchIndex: false,
    },
    quote_button_background_color: {
      type: "string",
      default: "#000000",
      storageKey: "EoXuhTc4WP-w",
      filterIndex: false,
      searchIndex: false,
    },
    quote_button_color: {
      type: "string",
      default: "#FFFFFF",
      storageKey: "FORNJcRtD3PD",
      filterIndex: false,
      searchIndex: false,
    },
    quote_button_font_style: {
      type: "string",
      storageKey: "Kav90z0dM9hX",
      filterIndex: false,
      searchIndex: false,
    },
    quote_button_hover_background_color: {
      type: "string",
      default: "#000000",
      storageKey: "_gxLOT-71HRR",
      filterIndex: false,
      searchIndex: false,
    },
    quote_button_hover_color: {
      type: "string",
      default: "#FFFFFF",
      storageKey: "Wa72THvQ-1dn",
      filterIndex: false,
      searchIndex: false,
    },
    quote_button_text: {
      type: "string",
      default: "Get Quote",
      storageKey: "cn_1u3vWHG0N",
      filterIndex: false,
      searchIndex: false,
    },
    quote_cancel_button_color: {
      type: "string",
      default: "#FFFFFF",
      storageKey: "-xiOYVJ00htw",
      filterIndex: false,
      searchIndex: false,
    },
    quote_cancel_button_text: {
      type: "string",
      default: "Cancel",
      storageKey: "U8_LjC2NgkrU",
      filterIndex: false,
      searchIndex: false,
    },
    quote_close_button_color: {
      type: "string",
      default: "#000000",
      storageKey: "MIiFdErMEmYj",
      filterIndex: false,
      searchIndex: false,
    },
    quote_popup_heading: {
      type: "string",
      default: "Please fill up this detail for Request Quote",
      storageKey: "0lsMPuR8TT-k",
      filterIndex: false,
      searchIndex: false,
    },
    quote_popup_heading_align: {
      type: "enum",
      default: "1",
      acceptMultipleSelections: false,
      acceptUnlistedOptions: false,
      options: ["1", "2", "3"],
      storageKey: "CZunTtCgdtVE",
      filterIndex: false,
      searchIndex: false,
    },
    quote_popup_heading_color: {
      type: "string",
      default: "#000000",
      storageKey: "clrAYnDseYzf",
      filterIndex: false,
      searchIndex: false,
    },
    quote_popup_title: {
      type: "string",
      default: "Request Quote",
      storageKey: "X1Y637_DKlta",
      filterIndex: false,
      searchIndex: false,
    },
    quote_popup_title_align: {
      type: "enum",
      default: "1",
      acceptMultipleSelections: false,
      acceptUnlistedOptions: false,
      options: ["1", "2", "3"],
      storageKey: "dKzpWKGlY480",
      filterIndex: false,
      searchIndex: false,
    },
    quote_popup_title_color: {
      type: "string",
      default: "#000000",
      storageKey: "BOBNWgOpPU5L",
      filterIndex: false,
      searchIndex: false,
    },
    quote_submit_button_background_color: {
      type: "string",
      default: "#008060",
      storageKey: "kiXeuZLhUJXM",
      filterIndex: false,
      searchIndex: false,
    },
    quote_submit_button_color: {
      type: "string",
      default: "#FFFFFF",
      storageKey: "Q6S1eCyvwdXK",
      filterIndex: false,
      searchIndex: false,
    },
    quote_submit_button_text: {
      type: "string",
      default: "Get Quote",
      storageKey: "QmaiL7ZPH5rb",
      filterIndex: false,
      searchIndex: false,
    },
    redirect_page: {
      type: "string",
      storageKey: "CeR0D8eyXwO_",
      filterIndex: false,
      searchIndex: false,
    },
    shop: {
      type: "belongsTo",
      parent: { model: "shopifyShop" },
      storageKey: "60fBm2-dTYq5",
      searchIndex: false,
    },
  },
  searchIndex: false,
};
